# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cfb5f5f50374604f0a389fcb02c304dbc6119ff9bc73d0da2627da6332c0a282d48f638bdb5df5df958c90e8e79dfb602d6215fa91bc0e986b428a11f3a1b85

test:
  secret_key_base: 02169a8a423c279e14844f198f434b37a07aa5346a959d58d7b85660f3834f6a7737c3e74c20c91ff7b4ab07240d96e6c9b8254cbd44f6056c5a7c1d369276b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
